version: "3.9"

services:
  db:
    image: postgres:trixie
    container_name: postgres_d_compose
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_DB_USER
      POSTGRES_PASSWORD: POSTGRES_DB_PASSWORD
      POSTGRES_DB: POSTGRES_DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
