# Generated by Django 5.2.6 on 2025-09-11 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6204e01-aefa-4fab-a953-5a50bb119f97'), editable=False, primary_key=True, serialize=False),
        ),
    ]
