# Generated by Django 5.2.6 on 2025-09-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_total_price_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
