# Generated by Django 5.2.6 on 2025-09-12 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_id_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb6a1f88-9598-4518-972a-373fc40ca66e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
