# Generated by Django 5.2.6 on 2025-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
