# Generated by Django 5.2.6 on 2025-09-12 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f70a1c29-30e4-4953-9171-5caebe393b2a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
