# Generated by Django 5.2.6 on 2025-09-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
