# Generated by Django 5.2.6 on 2025-09-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
