# Generated by Django 5.2.6 on 2025-09-17 12:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
