# Generated by Django 5.2.6 on 2025-09-17 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_library_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
